### ISSUE TITLE
Parallels 19 Blog Announcement

### ISSUE THREAD

**Issue by deric4** [Parallels/packer-examples#20]
Been anxiously waiting for 19 to drop since I saw changes in the plugin and the creation of this repo, so thank you to all involved 😄 !

I noticed that one of the links that points to this repo in the [blog post](https://www.parallels.com/blogs/parallels-desktop-19/
) uses a bad ref (branch was deleted?) https://github.com/Parallels/packer-examples/tree/add-macOs#readme

<img width="100%" alt="blog" src="https://github.com/Parallels/packer-examples/assets/5762138/a20ff068-972f-4bed-a19b-6dce4f4b4f6f">

**Comment by cjlapao** [comment]
Hi @deric4, I'm very happy you like it, and thanks for the feedback. Yeah, this was using a branch instead of the main one. I have requested the team to fix the link in the blog post and will let you know once it is fixed. Meanwhile, please let us know if there is any feature we should be adding.
