### ISSUE TITLE
Unknown source type parallels-iso

### ISSUE THREAD

**Issue by MikhailBystrov** [Parallels/packer-examples#31]
Following this documentation [windows-readme](https://github.com/Parallels/packer-examples/blob/main/windows/README.md)
I got this error:

```
windows git:(main) ✗ packer validate -var-file variables.pkrvars.hcl . 
Warning: Bundled plugins used

This template relies on the use of plugins bundled into the Packer binary.
The practice of bundling external plugins into Packer will be removed in an
upcoming version.

To remove this warning, add the following section to your template:


packer {
  required_plugins {
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
  }
}

Then run 'packer init' to manage installation of the plugins

Error: Unknown source type parallels-iso

  on build.pkr.hcl line 1:
  (source code not available)

known builders: [virtualbox-vm azure-chroot virtualbox-ovf azure-arm amazon-ebs
vsphere-iso vmware-vmx virtualbox-iso vagrant amazon-chroot googlecompute qemu
amazon-instance amazon-ebsvolume file vmware-iso docker amazon-ebssurrogate null
azure-dtl vsphere-clone]
```

My setup:
MacBook Pro M1

I installed:
`Packer` - by following this for macos [packer-install](https://developer.hashicorp.com/packer/downloads)
`PD-19` - already was on my laptop

Steps to reproduce:
1) clone repository
2) go to windows directory
3) change ``variables.TEMPLATE.pkrvars.hcl`` according to the [readme](https://github.com/Parallels/packer-examples/blob/main/windows/README.md)
```
iso_url      = "~/Downloads/win11-arm.iso" #path to your generated iso
iso_checksum = "" #the generated iso checksum in this format "sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", check readme in how to generate
machine_specs = {
  cpus      = 2,
  memory    = 8182,
  disk_size = "65536",
}
addons             = ["git", "vscode"]    # list of addons to be installed, check readme for more info
create_vagrant_box = false # set to true if you want to create a vagrant bo
```
4) rename ``variables.TEMPLATE.pkrvars.hcl`` to ``variables.override.pkrvars.hcl``
5) run:
```
packer validate -var-file variables.override.pkrvars.hcl .
```

**Comment by cjlapao** [comment]
did you install the packer-parallels plugin? with that output it seems it is not installed. while it should install it automatically it seems it did not
try
`packer init .` from within the folder

**Comment by MikhailBystrov** [comment]
I got it.
This file: [/windows/packer.hcl](https://github.com/Parallels/packer-examples/blob/main/windows/packer.hcl)
supposed to be: packer.pkr.hcl

**Comment by MikhailBystrov** [comment]
Also [iso_url](https://github.com/Parallels/packer-examples/blob/main/windows/variables.pkr.hcl#L29) and [iso_checksum](https://github.com/Parallels/packer-examples/blob/main/windows/variables.pkr.hcl#L33) are missing default values.

**Comment by MikhailBystrov** [comment]
I don't mean to sound cocky, but that's what I've been doing from the beginning.

When I run:
`packer build .`
I get this:
``` 
packer build .
Error: Unset variable "iso_url"

A used variable must be set or have a default value; see
https://packer.io/docs/templates/hcl_templates/syntax for details.

Error: Unset variable "iso_checksum"

A used variable must be set or have a default value; see
https://packer.io/docs/templates/hcl_templates/syntax for details.
```

https://github.com/Parallels/packer-examples/blob/main/ubuntu/variables.pkr.hcl#L54 - for some reason this file has default signature
https://github.com/Parallels/packer-examples/blob/main/windows/variables.pkr.hcl#L29 - and this file doesn't

variables.override.pkrvars.hcl content:
```
iso_url      = "/Users/mbystrov/Downloads/22621.1702.230505-1222.ni_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_en-us.iso" #path to your generated iso
iso_checksum = "86898b10512caa0f4841c425fe885efcd63dbe2dec6e99764f96921929964f16" #the generated iso checksum in this format "sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", check readme in how to generate
machine_specs = {
  cpus      = 2,
  memory    = 8000,
  disk_size = "65536",
}
addons             = ["git", "vscode"]    # list of addons to be installed, check readme for more info
create_vagrant_box = false # set to true if you want to create a vagrant box
```

**Comment by cjlapao** [comment]
As I explained, we do not supply a default value so that people supply it. In the linux case we can supply a default value as the logic inside the script will fill it in.
Windows is the only case where we do not supply, the reason being there is no public iso url, the user will need to sort it.
In the Ubuntu case because the isos are public we can have a default of empty string and this tells the script to go and use the latest 23.04 iso

https://github.com/Parallels/packer-examples/blob/8e88531c4c8b11c3760cbbc239300fa354474e96/ubuntu/provisioner.pkr.hcl#L13

When using `packer build .` you will then need to fill it in in the override but also need to notify the **packer build** that you have a different variable file, an override

so you should be using `packer build -var-file variables.override.pkrvars.hcl . `

This will then. tell packer to get the variables file and the values from the override

**Comment by MikhailBystrov** [comment]
Thanks, this really helped a bit, but then I got this:

```
➜  windows git:(main) ✗ packer build -var-file variables.override.pkrvars.hcl .
parallels-iso.image: output will be in this color.

Build 'parallels-iso.image' errored after 673 milliseconds 633 microseconds: Couldn't find Parallels Tools for the 'win-arm' flavor! Please, check the
value of 'parallels_tools_flavor'. Valid flavors are: 'win', 'lin',
'mac', 'os2' and 'other'

==> Wait completed after 673 milliseconds 666 microseconds

==> Some builds didn't complete successfully and had errors:
--> parallels-iso.image: Couldn't find Parallels Tools for the 'win-arm' flavor! Please, check the
value of 'parallels_tools_flavor'. Valid flavors are: 'win', 'lin',
'mac', 'os2' and 'other'
```
I think we can close this issue because we gone too far from the original message and I'm still running into the fact that for some reason I can't build this without the corrected Readme.

Perhaps it's my fault, because... I don't know packer.

**Comment by cjlapao** [comment]
@MikhailBystrov We saw that error in some of the Parallels Desktop installations. A reboot on that usually helped. At that point, we thought it might have been due to the beta version on our machines, but I will investigate it further.

Closing the ticket
