### ISSUE TITLE
Error 404 during fetching Ubuntu iso, wrong repository url

### ISSUE THREAD

**Issue by netandreus** [Parallels/packer-examples#34]
When I run ```packer build .``` I got an error, 404 file not found.

In [provisioner.pkr.hcl](https://github.com/Parallels/packer-examples/blob/main/ubuntu/provisioner.pkr.hcl#L13) path in line 13instead of
```
"https://releases.ubuntu.com/${var.version}/ubuntu-${var.version}-live-server-arm64.iso"
```
should be
```
"https://cdimage.ubuntu.com/releases/${var.version}/release/ubuntu-${var.version}-live-server-arm64.iso"
```

**Comment by cjlapao** [comment]
@netandreus Thanks for spotting this. I have now pushed a fix
