### ISSUE TITLE
macOS variable validation yields  "Error: Unsupported argument"

### ISSUE THREAD

**Issue by stephenulmer** [Parallels/packer-examples#52]
After creating a local variables file, running `packer validate -var-file variables.local.pkrvars.hcl .` results in an error.

```
ulmer@SLU-MacBook-Pro-2 macos % packer validate -var-file variables.local.pkrvars.hcl .
Error: Unsupported argument

  on build.pkr.hcl line 2:
  (source code not available)

An argument named "count" is not expected here.
```

Removing `count=0` from `build.pkr.hcl` makes the error go away, but I don't know if it affects anything else. I couldn't find any obvious references with grep, but I'm definitely not a packer expert.

This is variables.local.pkvars.hcl:
```
machine_name = "macOS-14.5"
machine_specs = {
  cpus   = 4,
  memory = 8192,
}
addons = [
]
create_vagrant_box = true
ipsw_url = "/Users/ulmer/Downloads/UniversalMac_14.5_23F79_Restore.ipsw"
```

I created #53, which just removes that line, just in case this looks like an obvious mistake to you.

**Comment by cjlapao** [comment]
yep, that was me leaving stuff where I shouldn't. it can be removed.
